2024-11-27 19:06:11,673 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2024-11-27 19:06:11,674 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Configure stats pid to 66023
2024-11-27 19:06:11,674 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Loading settings from /Users/shehvincent/.config/wandb/settings
2024-11-27 19:06:11,674 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Loading settings from /Users/shehvincent/Documents/Edge_Computing/NA_Model_Evaluation/Simulation/wandb/settings
2024-11-27 19:06:11,674 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-11-27 19:06:11,674 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-11-27 19:06:11,674 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-11-27 19:06:11,674 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-27 19:06:11,674 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-27 19:06:11,674 ERROR   MainThread:66023 [wandb_setup.py:_flush():81] error in wandb.init()
Traceback (most recent call last):
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/fy/9jbbbrm52gjb_tgk0yfq90c40000gn/T/ipykernel_66023/4004287167.py", line 6, in <module>
    wandb.init(
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1270, in init
    wandb._sentry.reraise(e)
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 161, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1255, in init
    wi.setup(kwargs)
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 304, in setup
    wandb_login._login(
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 347, in _login
    wlogin.prompt_api_key()
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 274, in prompt_api_key
    key, status = self._prompt_api_key()
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 253, in _prompt_api_key
    key = apikey.prompt_api_key(
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/lib/apikey.py", line 164, in prompt_api_key
    key = input_callback(api_ask).strip()
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort
2024-11-27 19:06:11,677 INFO    MainThread:66023 [wandb_init.py:_log_setup():533] Logging user logs to /Users/shehvincent/Documents/Edge_Computing/NA_Model_Evaluation/Simulation/wandb/run-20241127_190611-pa7wmur7/logs/debug.log
2024-11-27 19:06:11,677 INFO    MainThread:66023 [wandb_init.py:_log_setup():534] Logging internal logs to /Users/shehvincent/Documents/Edge_Computing/NA_Model_Evaluation/Simulation/wandb/run-20241127_190611-pa7wmur7/logs/debug-internal.log
2024-11-27 19:06:11,677 INFO    MainThread:66023 [wandb_init.py:init():619] calling init triggers
2024-11-27 19:06:11,677 INFO    MainThread:66023 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0005, 'batch_size': 64, 'gamma': 0.99, 'n_steps': 256, 'total_timesteps': 1000000}
2024-11-27 19:06:11,677 INFO    MainThread:66023 [wandb_init.py:init():669] starting backend
2024-11-27 19:06:11,677 INFO    MainThread:66023 [wandb_init.py:init():673] sending inform_init request
2024-11-27 19:06:11,684 INFO    MainThread:66023 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-11-27 19:06:11,755 INFO    MainThread:66023 [wandb_init.py:init():686] backend started and connected
2024-11-27 19:06:11,777 INFO    MainThread:66023 [wandb_run.py:_label_probe_notebook():1339] probe notebook
2024-11-27 19:06:11,786 INFO    MainThread:66023 [wandb_init.py:init():781] updated telemetry
2024-11-27 19:06:11,827 INFO    MainThread:66023 [wandb_init.py:init():814] communicating run to backend with 120.0 second timeout
2024-11-27 19:07:21,790 WARNING MainThread:66023 [wandb_init.py:init():1260] interrupted
Traceback (most recent call last):
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1256, in init
    return wi.init()
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 817, in init
    result = run_init_handle.wait(
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
2024-11-27 19:07:25,189 INFO    MainThread:66023 [wandb_settings.py:_apply_login():1989] Applying login settings: {}
2024-11-27 19:07:25,196 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2024-11-27 19:07:25,196 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Configure stats pid to 66023
2024-11-27 19:07:25,196 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Loading settings from /Users/shehvincent/.config/wandb/settings
2024-11-27 19:07:25,196 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Loading settings from /Users/shehvincent/Documents/Edge_Computing/NA_Model_Evaluation/Simulation/wandb/settings
2024-11-27 19:07:25,196 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-11-27 19:07:25,196 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-11-27 19:07:25,196 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-11-27 19:07:25,197 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-27 19:07:25,197 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-27 19:07:25,197 ERROR   MainThread:66023 [wandb_setup.py:_flush():81] error in wandb.init()
Traceback (most recent call last):
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/fy/9jbbbrm52gjb_tgk0yfq90c40000gn/T/ipykernel_66023/4004287167.py", line 6, in <module>
    wandb.init(
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1270, in init
    wandb._sentry.reraise(e)
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 161, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1255, in init
    wi.setup(kwargs)
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 304, in setup
    wandb_login._login(
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 347, in _login
    wlogin.prompt_api_key()
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 274, in prompt_api_key
    key, status = self._prompt_api_key()
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 253, in _prompt_api_key
    key = apikey.prompt_api_key(
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/lib/apikey.py", line 164, in prompt_api_key
    key = input_callback(api_ask).strip()
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort
2024-11-27 19:07:25,198 INFO    MainThread:66023 [wandb_init.py:_log_setup():533] Logging user logs to /Users/shehvincent/Documents/Edge_Computing/NA_Model_Evaluation/Simulation/wandb/run-20241127_190725-zyynrsm8/logs/debug.log
2024-11-27 19:07:25,198 INFO    MainThread:66023 [wandb_init.py:_log_setup():534] Logging internal logs to /Users/shehvincent/Documents/Edge_Computing/NA_Model_Evaluation/Simulation/wandb/run-20241127_190725-zyynrsm8/logs/debug-internal.log
2024-11-27 19:07:25,198 INFO    MainThread:66023 [wandb_init.py:init():619] calling init triggers
2024-11-27 19:07:25,198 INFO    MainThread:66023 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10}
2024-11-27 19:07:25,198 INFO    MainThread:66023 [wandb_init.py:init():669] starting backend
2024-11-27 19:07:25,198 INFO    MainThread:66023 [wandb_init.py:init():673] sending inform_init request
2024-11-27 19:07:25,200 INFO    MainThread:66023 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-11-27 19:07:25,204 INFO    MainThread:66023 [wandb_init.py:init():686] backend started and connected
2024-11-27 19:07:25,209 INFO    MainThread:66023 [wandb_run.py:_label_probe_notebook():1339] probe notebook
2024-11-27 19:07:25,215 INFO    MainThread:66023 [wandb_init.py:init():781] updated telemetry
2024-11-27 19:07:25,239 INFO    MainThread:66023 [wandb_init.py:init():814] communicating run to backend with 90.0 second timeout
2024-11-27 19:07:25,658 WARNING MsgRouterThr:66023 [router.py:message_loop():75] message_loop has been closed
2024-11-27 19:08:55,695 ERROR   MainThread:66023 [wandb_init.py:init():841] encountered error: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2024-11-27 19:08:55,700 ERROR   MainThread:66023 [wandb_init.py:init():1266] error in wandb.init()
Traceback (most recent call last):
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1256, in init
    return wi.init()
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 847, in init
    raise error
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2024-11-27 19:09:44,262 INFO    MainThread:66023 [wandb_settings.py:_apply_login():1989] Applying login settings: {}
2024-11-27 19:09:44,267 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Current SDK version is 0.18.7
2024-11-27 19:09:44,267 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Configure stats pid to 66023
2024-11-27 19:09:44,267 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Loading settings from /Users/shehvincent/.config/wandb/settings
2024-11-27 19:09:44,267 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Loading settings from /Users/shehvincent/Documents/Edge_Computing/NA_Model_Evaluation/Simulation/wandb/settings
2024-11-27 19:09:44,267 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-11-27 19:09:44,268 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-11-27 19:09:44,268 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-11-27 19:09:44,268 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-27 19:09:44,268 INFO    MainThread:66023 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-11-27 19:09:44,268 ERROR   MainThread:66023 [wandb_setup.py:_flush():81] error in wandb.init()
Traceback (most recent call last):
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/fy/9jbbbrm52gjb_tgk0yfq90c40000gn/T/ipykernel_66023/4004287167.py", line 6, in <module>
    wandb.init(
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1270, in init
    wandb._sentry.reraise(e)
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/analytics/sentry.py", line 161, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1255, in init
    wi.setup(kwargs)
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 304, in setup
    wandb_login._login(
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 347, in _login
    wlogin.prompt_api_key()
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 274, in prompt_api_key
    key, status = self._prompt_api_key()
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_login.py", line 253, in _prompt_api_key
    key = apikey.prompt_api_key(
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/lib/apikey.py", line 164, in prompt_api_key
    key = input_callback(api_ask).strip()
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort
2024-11-27 19:09:44,268 INFO    MainThread:66023 [wandb_init.py:_log_setup():533] Logging user logs to /Users/shehvincent/Documents/Edge_Computing/NA_Model_Evaluation/Simulation/wandb/run-20241127_190944-j5ij55vz/logs/debug.log
2024-11-27 19:09:44,268 INFO    MainThread:66023 [wandb_init.py:_log_setup():534] Logging internal logs to /Users/shehvincent/Documents/Edge_Computing/NA_Model_Evaluation/Simulation/wandb/run-20241127_190944-j5ij55vz/logs/debug-internal.log
2024-11-27 19:09:44,268 INFO    MainThread:66023 [wandb_init.py:init():619] calling init triggers
2024-11-27 19:09:44,269 INFO    MainThread:66023 [wandb_init.py:init():626] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.0005, 'batch_size': 64, 'gamma': 0.99, 'n_steps': 256, 'total_timesteps': 1000000}
2024-11-27 19:09:44,269 INFO    MainThread:66023 [wandb_init.py:init():669] starting backend
2024-11-27 19:09:44,269 INFO    MainThread:66023 [wandb_init.py:init():673] sending inform_init request
2024-11-27 19:09:44,272 INFO    MainThread:66023 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-11-27 19:09:44,273 INFO    MainThread:66023 [wandb_init.py:init():686] backend started and connected
2024-11-27 19:09:44,286 INFO    MainThread:66023 [wandb_run.py:_label_probe_notebook():1339] probe notebook
2024-11-27 19:09:44,293 INFO    MainThread:66023 [wandb_init.py:init():781] updated telemetry
2024-11-27 19:09:44,312 INFO    MainThread:66023 [wandb_init.py:init():814] communicating run to backend with 300.0 second timeout
2024-11-27 19:11:03,792 WARNING MainThread:66023 [wandb_init.py:init():1260] interrupted
Traceback (most recent call last):
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1256, in init
    return wi.init()
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 817, in init
    result = run_init_handle.wait(
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/site-packages/wandb/sdk/lib/mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/threading.py", line 581, in wait
    signaled = self._cond.wait(timeout)
  File "/Users/shehvincent/anaconda3/envs/edge_computing/lib/python3.9/threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
